# Lab3.1 Machine learning basics

Copyright: Vrije Universiteit Amsterdam, Faculty of Humanities, CLTL

RMA/Text Mining MA, Introduction to HLT

This notebook explains the simple basics of machine learning. At the end of this notebook, you learned:

- the basic principles of machine learning for text classification
- how features are represented as vectors
- how to train a classifier from vector representations
- how to train and apply a classifier to text represented as feature vectors
- what a bag-of-words representation is
- what the information value (TF*IDF) of a word is

**Background reading:**

NLTK Book
Chapter 6, section 1 and 3: https://www.nltk.org/book/ch06.html



## 1. Machine Learning schema

The overall process of machine learning is shown in the next image that is taken from Chapter 6 of the NLTK book. In general, machine learning consists of a training phase in which an algorithm associates data features with certain labels (e.g. sentiment, part-of-speech). The training results in a classifier model that can be applied to unseen data. The classifier compares the features of the unseen data with the previously seen data and makes a prediction of the label on the basis of some similarity calculation.

![title](images/ml-schema.png)


Crucial in this process is 1) the features that represent the data (in our case text) and 2) the algorithm that is used. In this course, we are not going to discuss the various machine learning algorithms in depth but we focus on the text features and how they are represented as so-called feature vectors. In the case of a text, we need to define what properties characterize a text. These properties are transformed into a feature vector representation that the algorithm can handle. The algorithm will create an association between the representation and interpretation labels that are manually assigned, e.g. the sentiment or topic of a text. It will ```learn``` which features are good predictors and which features are not. When given an unseen text, it will represent the text using the same feature vectors and make a prediction about the label using the learned feature associations.

**Preparations**

We are going to use the Scikit-learn package to transform the feature values into a vector representation and learn the associations with some label:

https://scikit-learn.org/stable/install.html

Scikit-learn is a package that contains a lot of machine learning algorithms and functions for dealing with features, training a model and carrying out evaluation and error analysis. To install it run one of the following commands from the command line:

- pip install -U scikit-learn

or
 
- conda install scikit-learn


In [1]:
!pip install -U scikit-learn
#!conda install scikit-learn

  Using cached scikit_learn-1.5.1-cp310-cp310-macosx_10_9_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 9.0 MB/s eta 0:00:0000:0100:01m
  Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
  Using cached scipy-1.14.0-cp310-cp310-macosx_14_0_x86_64.whl (25.5 MB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)

[notice] A new release of pip is available: 23.0.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip


We are also using a package called "numpy": https://numpy.org. *Numpy* is a package for representing numerical and vector representations in Python.

Install "numpy" from the command line following the instructions on the website. After installing, you can import it.

In [2]:
!pip install numpy
#%conda install numpy


[notice] A new release of pip is available: 23.0.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip


### 1.1 Vector representations


Before we turn to a text example, we are going to use a very simple data set. We show how to train and evaluate an SVM (Support-Vector-Machine) using a made-up example of multi-class classification for a non-linguistic dataset. The goal is to predict someone's weight category (say: skinny, fit, average, overweight) based on their properties.

We use three features:

* **age in years**
* **height in cms**
* **number of ice cream cones eaten per year**

For each of these features a person has a value, e.g. 45, 178, 100. We can thus represent a person as an array of numbers:

```[45, 178, 100]```

The feature representation for 5 people will then be a list of 5 arrays (which is called a matrix). Each array in the list represents the data for a single person.

Each row (or person) is represented by an array of numbers in which the first is the age, the second the height in cms and the third the number of cones per year: 

In [4]:
X = [[30, 180, 1000], 
     [80, 180, 100],
     [50, 180, 100],
     [40, 160, 500],
     [15, 160, 400]
    ]

The first person is thus 30 years old, 180 cms tall and eats 1000 cones per year. The next command prints the data for the first instance.

In [4]:
print('First instance in the data set X =', X[0])

First instance in the data set X = [30, 180, 1000]


An array of numbers in which each position holds a value for a specific feature is what we call a feature vector. This person is 30 years old, 180 cm tall and eats 1000 cones per year.

For all our data in the data set we must have a feature vector of the same length. If there is no value for feature, we still need to represent it but the value will be zero.

In addition to the data that is now assigned to the variable 'X', we also need to have the prediction that goes with the instances. For this we use another array with the values that we assign to the variable 'Y'. 

In [6]:
Y = ["overweight", 
     "skinny",
     "fit",
     "average",
     "average"]

We need to have as many values as we have instances in our data set, as the software pairs the elements in X with the elements in Y. Obviously, the values should also be in the correct order to correspond with the instances!

In [7]:
print('The length of the data set =', len(X))
print('The length of the predictions =', len(Y))
print('The first prediction =', Y[0], 'which is true for the first person', X[0])

The length of the data set = 5
The length of the predictions = 5
The first prediction = overweight


A nice function to pair lists in Python is the "zip" function which creates a list of tuples from two lists. If the lists do not have the same length, it will generate an error message. We can use this to pair the instances with their labels:

In [8]:
for instance, label in zip(X, Y):
    print(instance, label)

[30, 180, 1000] overweight
[80, 180, 100] skinny
[50, 180, 100] fit
[40, 160, 500] average
[15, 160, 400] average


If the lists do not have the same length, ```zip``` will generate an error message. 

### 1.2 Using Skikit learn to build a classifier

Now that we have the data and the predictions, we can train a model. We are going to use the **svm** module from **sklearn**, from which we will select the **LinearSVC** (Linear Support Vector Classification: https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html) class. Support Vector Machines or SVMs are powerful supervised machine learning functions that find the optimal division (a so-called hyperplane in a multidimensional data space) between positive and negative examples of a class. For now it is not important to know the details about this algorithm. You will learn about that in the machine learning course. 


We first import *svm* from sklearn and next we instantiate a model with the variable name 'lin_classifier' (any name will do and you can instantiate as many variables as you want until your run out of memory). We will use this instantiation for training and classifying.

In [3]:
from sklearn import svm

lin_classifier = svm.LinearSVC()

Now we train the model ```lin_classifier``` by feeding it with the data set 'X' and the predictions 'Y'. Feeding we do with the 'fit' function. The 'fit' function creates the model and adds the data to it. The model is defined by the number of properties in the data but also by the order of the properties. So the current data example has 3 properties and the first position has the values for the age and not something else.

In [10]:
lin_classifier.fit(X,Y)

LinearSVC()

### 1.3 Using Sklearn to classify unseen data

Let's now apply the model to a new instance 'Z'. What does our trained SVM instance think about the weight category of an instance who is 18 years old, 171cm tall, and who eats 400 ice cream cones per year? We can use the *predict* function of our classifier instance to tell us:

In [12]:
## represent a new instance using the same vector representation
Z=[[18, 171, 450]]
predicted_label = lin_classifier.predict(Z)
print(predicted_label)

['average']


Apparently the SVM instance thinks it is **average**, which is not surprising since **number of ice cream cones eaten per year** and **height** seem to correlate highly with the weight categories.

Note that we people reason with some (weak) causal explanatory model but our Machine Learning model just uses data patterns and association. It does not know why the answer *average* makes sense or not.

## 2. Representing a text as a Bag-Of-Words

So now let's move from people to text. When we process language, we typically want to represent each text by the linguistic features. So in the data structure, each row will now be a piece of text (as rows were people in the previous example) and the array will have values for different properties of the text. Instead of predicting the *weight*, we now want to predict interpretations of the text, such as its sentiment or the topic.

A critical component of almost any machine learning approach is **feature representation**. 
This is not so strange since we need to somehow convert a complex text, e.g., words, sentences, a tweet, or a document, into something numerical that can be interpreted by a computer, and is also useful for the learning we want to do.

A text consists of a sequence of words on which we impose syntax and semantics. A machine needs to learn to associate the structural properties of the text with some interpretation. We can use various language properties to do this, both structural and external:

- the words and their frequency in a text
- the part-of-speech of words
- grammatical relations such as dependencies
- combinations of words: sequences of three words, four words, phrases, sentences
- the characters that make up the words
- the meaning of words or combinations of words
- word length, sentence length, word position in a text or a sentence
- discourse structure: title, header, caption, body, conclusion sections
- etc....

Which features work often depends on the kind of task and is usually determined experimentally.

Some of the above structural properties we get for free if we split a text into words. Other properties are not explicit, such as the part-of-speech of words, phrases, syntax and their meaning.

For now, we are only considering the words of a text as features. In fact, we are going to ignore the order of the words and consider a text as a *Bag-Of-Words*.

### 2.1 Bag of words

We are going to create a vector representation of a text in which the words are the features that characterize the content of the text. To keep things simple, we ignore the order of the words but we do want to know how often a word occurs in a document so that we can give it a weight.

In our vector representation we want each word to occupy a unique position in the array just as the age [0], length [1] and number of cones [2] in our *weight* prediction example. That means that our vector needs to be as long as the number of words that we may find in the texts. For this we need to first read all the text and extract all the unique words that occur, i.e. the vocbulary. Next, we create a vector that is as long as the vocabulary list such that each position corresponds to a unique word. Note that the order of the vector matters but we do not represent the order of the words in a text.

Next, we can represent each document by this vector array by adding a row for a document (an instance of a text) where we score each position with the frequency of this word in the text. If a word from the vocabulary does not occur in a specific text, the va;ue remains zero.

Let's look at an example.

In [15]:
sents = ['A rose is a rose',
         'A rose stinks',
         "A book is nice"]

Our variable ```sents``` has a list as a value that contains three sentences, each with different words. If we ignore the case, these sentences contain six unique words: 

```['a', 'rose', 'is', 'stinks', 'book', 'nice']```

In order to represent the words of these sentences, we thus need a vector with six slots corresponding to the above list. Representing the three sentences as a word-feature vectors would look as follows:

In [16]:
vocabulary = ['a', 'rose', 'is', 'stinks', 'book', 'nice']
print('Length of the vocabulary', len(vocabulary))
vector_sents = [[2,2,1,0,0,0],
                [1,1,0,1,0,0],
                [1,0,1,0,0,1]]

Length of the vocabulary 6


Try to check the counts to reconstruc the sentences. Here we only have three short sentences but what if we have many thousands. It would be impossible to do this manually.

To do all the above, sklearn provides a function that does all the work for us:

* CountVectorizer: turns a textual data set into a vector representation consisting of a vector array with frequency counts and a vocabulary that maps each word to the corresponding vector array position

We will import this function together with *numpy* and *nltk*.

In [17]:
import numpy
from sklearn.feature_extraction.text import CountVectorizer
import nltk

We use the **CountVectorizer** function to create the bag of words representation from the above texts just as we did manually. It requires two parameters to be set in advance when we create an instance of the CountVectorizer: 1) the minimal number of documents in which the term should occur (number of rows in our data) and 2) what tokenizer should be used to split the text into separate tokens (words). Since our data set is small, we set the minimal number of document occurrences to "1". As a tokenizer to split the text, we use NLTK. We first need to create an instance *our_vectorizer* with these settings fr the paramter *mind_df* and *tokenizer*:

In [19]:
# you can adapt min_df to restrict the representation to more frequent words e.g. 2, 3, etc.. if the data set is bigger
our_vectorizer = CountVectorizer(min_df=1, # in how many documents the term minimally occurs
                             tokenizer=nltk.word_tokenize) # we use the nltk tokenizer to split the text into tokens

Check the API of scikit learn to see what other paramters can be used:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

Note there is also a parameter max_df to ignore words that occur in more documents than specified. This can be convenient to exclude words that occur everywhere and do not discriminate.

After creating ```our_vectorizer``` as an instance of **CountVectorizer**, we can feed it with our sentences to make it create vector representations for each. A **CountVectorizer** has a function ```fit_transform``` that can take a list of texts (sentences) as input and will 1) extract all the words that occur in all texts, 2) create vector model from these words and 3) represents each text according to this model by counting which words occur in each text. This will give us two things:

* a data structure that represents the sentences through their vectors
* the vocabulary that maps to the columns of the data structure

The result of calling this function is assigned to the variable *sents_vector_data*. 

In [21]:
sents_vector_data = our_vectorizer.fit_transform(sents)

### WARNING: ```fit_transform``` of *CountVectorizer* is NOT the same as ```fit``` used for our classifier! Can you formulate the difference in your own words?

Let's us now inspect the ```sents_vector_data``` object created by ```our_vectorizer```. The data representation of the text is assigned to the variable ```sents_vector_data```. The vocabulary is stored in the ```our_vectorizer```.

We first look at the type of class for ```sents_vector_data```. It is a special sklearn class (csr_matrix) especially designed for large and sparse vectors. Various functions and attributes are provided. We are going to look at the *shape* attribute. Printing the so-called ```shape``` of sents_counts shows us the dimensions of the matrix. It tells us we have 3 rows and 6 columns to represent the data.

In [22]:
print(type(sents_vector_data))
print(sents_vector_data.shape)
# sents_counts has a dimension of 3 (document count) by 6 (# of unique words)

<class 'scipy.sparse._csr.csr_matrix'>
(3, 6)


'csr' stands for a compressed sparse row. A matrix of 'csr' is a list of such rows, i.e. a table with rows and columns.

The actual data now looks as follows (note that we have to convert the ```csr_matrix``` to an **array** to print it):

In [25]:
print('The vector representation of the sentences looks as follows:')
print (sents_vector_data.toarray())

The vector representation of the sentences looks as follows:
[[2 0 1 0 2 0]
 [1 0 0 0 1 1]
 [1 1 1 1 0 0]]


Great!! Now the columns stand for words and the rows are the sentences or pieces of text. This looks very similar to the text vectors that we created manually but they are not exactly the same. This is because the order in the vocabulary is different.

Let's check the vocabulary now, which is stored in ```our_vectorizer```:

In [26]:
# this vector is small enough to view in full! 
print('The vocabulary of all the sentences  consists of the following words:', 
      list(our_vectorizer.vocabulary_.keys()))
print('These words are mapped to the data columns as feature names:', 
      our_vectorizer.get_feature_names_out())

The vocabulary of all the sentences  consists of the following words: ['a', 'rose', 'is', 'stinks', 'book', 'nice']
These words are mapped to the data columns as feature names: ['a' 'book' 'is' 'nice' 'rose' 'stinks']


Look carefully at the list. Notice that they contain the same words but in different order The first is the vocabulary and the second lists the names of the features in the order of the columns in our matrix. The order of the columns is also different from the order of our manually created vectors.

Through the feature name, we can now recover the three texts from the previous data array. If we find a value greater than zero in a cell, the word occurs in a text otherwise not. The first row represents: 'A rose is a rose'. It has 6 positions representing the complete vocabulary. The first position represents the first word "a" and it has value '2', which means it occurs twice in the sentence. The fourth slot is for "is" which occurs once and the fifth slot is for "rose" which occurs twice. The other slots are zero because these words do not occur in the first sentence.

Obviously, we cannot recover the order of the words in the text, as this is a bag-of-word representation.

### 2.2 Training a classifier with word vectors
Now we have seen how we can turn a text into a vector representation. We can associate these text representations with labels as we have seen above for predicting somebody's weight. We now use different labels but note that for the algorithm the labels are meaningless. They could be numbers or any set of words.

It is not so difficult to see how we can train an SVM instance with the data. All we need is to pair a set of labels to the data instances. Let's use sentiment values: ```neutral```, ```negative``` and ```positive```. You can also use other labels such as ```A```, ```B```, ```C```. Obviously, we need as many labels as our number of sentences and in the right order so that we can pair them. This is our annotation of the texts:

In [23]:
sentiment_labels=["neutral", "negative", "positive"]

To pair the labels with the text representations, we use the ```zip``` function again. The result is a list of pairs that we can iterate over and get the text with the corresponding label:

In [24]:
for instance, label in zip(sents_vector_data.toarray(),sentiment_labels):
    print(instance, label)

[2 0 1 0 2 0] neutral
[1 0 0 0 1 1] negative
[1 1 1 1 0 0] positive


We have nicely paired sentence representations and sentiment values. Let's train and test an SVM. To train the model, we use the *fit* function of the svm as before. We feed it with the sents_vector_data generated by *our_vectorizer* with the labels.

In [25]:
from sklearn import svm

lin_classifier = svm.LinearSVC()
lin_classifier.fit(sents_vector_data,sentiment_labels)

LinearSVC()

No serious errors, so our classifier is now trained.

### 2.3 Classifying a new text with our text classifier

Now we want to apply this classifier to a new text. To do so, we need to create a vector representation for this text according to the model that we derived for the training data. This means, we can **ONLY(!!!)** use words that are also used in the training data. We **CANNOT** represent words that are not in the training data in our model. Furthermore, we need to represent  words that do in the right order. The feature names stored in the vectorizer present the vocabulary in the right order:

In [26]:
new_text="a good book is a rose"
print(our_vectorizer.get_feature_names_out())

['a' 'book' 'is' 'nice' 'rose' 'stinks']


We thus need to create an array with the length of the training vocabulary and add the counts of these words on the basis of the new text. This would look as follows:

In [9]:
new_text_vector=[[2, 1, 1, 0, 1, 0]]

In this representation, the word **good** is thus not represented, and the words **nice** and **stinks** do not occur in the new text and therefore have value ```0```. The word "a" occurs twice, "book" and "is" occur once.

Obviously, we do not want to do this manually for each new text. Sklearn's **vectorizer** has another function to automatically represent any text according to the learned model. We use the function *transform* which transforms data into the representation of a given model. This literally means represent the text according to the vocabulary of the training data.

**Note (!!!!)** that we do NOT use the function ```fit_transform``` here. What will happen if you did? Think about it ....

In [27]:
new_text_vector = our_vectorizer.transform([new_text]).toarray()
print(new_text_vector)

[[2 1 1 0 1 0]]


We see that we automatially get the same result as we created manually before.

Now it is time to let our classifier ```lin_classifier``` make a prediction. For this we use the ```predict``` function and pass the ```new_text_vector``` representation as input.

In [28]:
predicted_label = lin_classifier.predict(new_text_vector)
print(predicted_label)

['neutral']


The prediction is *neutral* which makes sense since none of the distinguishing words "nice" and "stinks" occur in the text. So let's manipulate the data and turn the value for "stinks" to "1":

In [29]:
new_text_vector=[[2, 1, 1, 0, 1, 1]]

In [30]:
predicted_label = lin_classifier.predict(new_text_vector)
print(predicted_label)

['negative']


That did help.

### 2.2 TF-IDF
One big problem for the bag of words approach is that it treats all words as equal. Why is that a disadvantage? It means that words that occur in many documents, such as *"a"*, contribute heavily to the decision making of the machine learning approach whereas other words may be much more informative, e.g., **nice**. TF-IDF (Term Frequency multiplied by the Inverse Document Frequency) addresses this problem by scoring words for their frequency in a document (Term Frequency) but assigning less weight to words that occur in many documents. Here is a [blog](https://www.freecodecamp.org/news/how-to-process-textual-data-using-tf-idf-in-python-cd2bbc0a94a3) that provides more information about TF-IDF.

TF-IDF is a concept from the information retrieval research. You can image that it matters for information retrieval to measure how discriminative words are across different documents. For other applications such as sentiment classification, it is less clear what the value is. Here we are going to apply it anyway and see what it does to the representation.

The next cell shows how to apply **TF-IDF** using sklearn. We create an instance ```tfidf_transformer``` of the class *TfidTransformer* to feed it the bag-of-words presentation that we created before with **our_vectorizer**. We then use the ```fit_transform``` function to produce a representation with the TF-IDF values for the words which replaces the former count values.

In [31]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
sents_tfidf = tfidf_transformer.fit_transform(sents_vector_data)

To inspect the result, we need to convert it to an *array*. 

In [32]:
tf_idf_array = sents_tfidf.toarray()
print(our_vectorizer.get_feature_names_out())
print(tf_idf_array)

['a' 'book' 'is' 'nice' 'rose' 'stinks']
[[0.57048339 0.         0.36730061 0.         0.73460123 0.        ]
 [0.42544054 0.         0.         0.         0.54783215 0.72033345]
 [0.34520502 0.5844829  0.44451431 0.5844829  0.         0.        ]]


To get rounded values, we can use a *numpy* function:

In [34]:
print(our_vectorizer.get_feature_names_out())
print(numpy.round(tf_idf_array, decimals=2))

['a' 'book' 'is' 'nice' 'rose' 'stinks']
[[0.57 0.   0.37 0.   0.73 0.  ]
 [0.43 0.   0.   0.   0.55 0.72]
 [0.35 0.58 0.44 0.58 0.   0.  ]]


##### This is an expected result! 

In the bag of words approach, The words **"a"** and **"book"** both had a frequency of 1 in the third sentence. Now that we've applied the TF-IDF approach, we see that the word *book* has a higher weight (0.58) than the word "*a*" (0.43) in the third sentence since "*a*" occurs in all three sentences and "*book*" only in one. Can you tell why in the first sentence "*a*" scores 0.57?

Let's try again training a model with the new data representation with the function *fit*:

In [35]:
lin_classifier_weight = svm.LinearSVC()
lin_classifier_weight.fit(tf_idf_array,sentiment_labels)

LinearSVC()

Now, to test the new sentence we must apply the same transformations we did to the training data. This means we also have to represent the new sentence using TF-IDF weights.

In [36]:
#redefine new test without manipulation
new_text_vector=[[2, 1, 1, 0, 1, 0]]

# transform the counts to tf-idf features
new_tf_idf_text_vector = tfidf_transformer.transform(new_text_vector)

new_tf_idf_array = new_tf_idf_text_vector.toarray()
print(our_vectorizer.get_feature_names_out())
print(numpy.round(new_tf_idf_array, decimals=2))

['a' 'book' 'is' 'nice' 'rose' 'stinks']
[[0.63 0.53 0.4  0.   0.4  0.  ]]


Note that although the word "*book*" is assigned a high weight (0.53), the TF-IDF approach still gets confused with the test data and assigns a higher weight to the word "*a*". Why is this?

Finally, we can use the new trained model with the new representations to get a prediction

In [37]:
predicted_label = lin_classifier_weight.predict(new_tf_idf_text_vector)
print(predicted_label)

['neutral']


Sadly, the difference in representation did not lead to a different prediction. 

It is important to see two things in this example:

<ol>
<li> Regardless of the changes we made in representing the data, the model cannot process words that it has not seen, such as "*good*". 
<li> The model does not know that unseen words can be **semantically** related to words that it has seen. For example, the model does not know that the word "*good*" is related to "*nice*".
</ol>

One way to fix the these problems would be by having a larger (training) dataset with more diverse words. 

## Summary

What are the important functions to remember?

Two packages to turn text data into vector representations **CountVectorizer** and **TfidfTransformer**:

* **fit_transform**: used for the training data from which it 1) extracts (fit) a bag of words as features and 2) represents (transform) each training document according to the vector
* **transform**: applied to test data to represent it according to the vector model of the training data

From sklearn you can import various classifiers such as NaiveBayes or SVM. All classifiers come with at least two functions:

* **fit**: learn from the training data the association between the vector representations and the labels
* **predict**: apply the model to a vector representation to predict the associated label


## End of this notebooks.